### ISSUE TITLE
[Bug] Array Index is out of range when setting parameters to 7 or more

### ISSUE THREAD

**Issue by ap-ch** [axl89/unity-2d-topdown-example#1]
`timetable.cs`

Each slot sets `one` and `two` to the needed value (position x,y) when they are clicked. Vertical slot **1,7** breaks the code (have not tried with rest of them, but they are supossed to work the same way).
Works nice with other coordinates.

**Comment by axl89** [comment]
Arrays use 0-based numbering (see [here](https://en.wikipedia.org/wiki/Zero-based_numbering)), which means that the first element of the array is 0, and the last is N-1, being N the length of your array.

If you want to access the Vertical slot 1,7, you should do something like `buttons[0,6]`
